### ISSUE TITLE
Replace O/X text with images

### ISSUE THREAD

**Issue by linkret** [linkret/CrosseyCircley#14]
On the game grid, currently text is used, but it would be a lot prettier if it were images instead. Or at least some pretty, nicely detailed font?

**Comment by SVredeveld** [comment]
Hi, 
I've tried some different images to use instead of the text. If you could tell me which of these three you would prefer, I could make a PR ready for it. 😄 

1: 
![image](https://user-images.githubusercontent.com/10913197/137781857-57db7ad2-3bcc-4f3b-8ed8-602d01cdc71e.png)

2: 
![image](https://user-images.githubusercontent.com/10913197/137781917-d166e418-e6dc-4d97-b717-8358138c2d06.png)

3: 
![image](https://user-images.githubusercontent.com/10913197/137781975-1ade05ff-a1e6-44b8-8b4f-9eacf873e966.png)

 Or a different type, if you don't like any of these 😉

**Comment by linkret** [comment]
I think the second one looks a bit scruffy, but both 1st and 3rd look great! Looking forward to the PR.
